Back button tooltip for Preview component
HCL-TECH-SOFTWARE/enchanted-react-components pull request #77
Opened 2024-12-23 04:54 UTC by code4hub

2024-12-23 09:03 UTC, PiyushKashyapHCL approved these changes

2025-01-07 07:46 UTC, felix-hcl requested changes
Clarification regarding breaking change needed

2025-01-07 07:46 UTC, felix-hcl commented on src/Preview/Preview.tsx
> +    backButton: string;
is this new property really **required** and not **optional**?
If so, this would lead to a breaking change. Currently the changelog only states a change and not a breaking change.

2025-01-07 08:01 UTC, code4hub commented on src/Preview/Preview.tsx
> +    backButton: string;
Updated the changelog with the breaking change. Thanks

2025-01-07 08:03 UTC, felix-hcl approved these changes

2025-01-07 08:03 UTC, merged